---
- name: Deploy Spring Boot
  hosts: app
  vars:
    ci_cd_namespace: coo-ci-cd
    dev_namespace: coo-dev
    test_namespace: coo-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
